### ISSUE TITLE
Show DropOff Option

### ISSUE THREAD

**Issue by bugsbunnyshah** [slydogshah/appGalCloud#34]
Need the UX screen that displays DropOff Options to someone placing a PickUpRequest. The flow is:

Start PickUpRequest -> Collect PickUpDetails -> Show DropOff Options

This is the payload that needs to be rendered
{
        "id": "234fe6c0-bd48-40e2-a4c8-906c7456f235",
        "sourceOrg": {
            "orgId": "microsoft",
            "orgName": "Microsoft",
            "orgContactEmail": "melinda_gates@microsoft.com",
            "location": {
                "latitude": 30.25860595703125,
                "longitude": -97.74873352050781
            },
            "producer": true
        },
        "foodRunner": {
            "profile": {
                "id": "7344b235-5098-4358-94cf-ca23a9af7eda",
                "email": "bugs.bunny.shah@gmail.com",
                "mobile": 8675309,
                "photo": "",
                "password": "",
                "profileType": "FOOD_RUNNER"
            },
            "location": {
                "latitude": 30.25860595703125,
                "longitude": -97.74873352050781
            }
        },
        "start": 1614168000,
        "notificationSent": true,
        "dropOffNotes": [
            
        ]
    }

API Call is: GET: http://localhost:8080/notification/dropOffOrgs/?orgId=microsoft

**Comment by Tarun747** [comment]
In order to update and ux for **pickup request**  form we made changes to home.js components for readable and scaleable code and used Google  chart library [[link](https://developers.google.com/chart)]



![Screenshot 2021-03-04 at 1 32 56 AM](https://user-images.githubusercontent.com/39861004/109865009-8e9dc480-7c89-11eb-8977-0336da45abbf.png)



![Screenshot 2021-03-04 at 1 33 30 AM](https://user-images.githubusercontent.com/39861004/109865055-a2492b00-7c89-11eb-89c5-5efdc006c68a.png)
